# Generated by Django 5.0.6 on 2024-06-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("descargas_datos", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Link",
        ),
    ]
