# Generated by Django 5.0.6 on 2024-07-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("descargas_datos", "0002_delete_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scraper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("titulo", models.CharField(blank=True, max_length=255, null=True)),
                ("articulo", models.TextField(blank=True, null=True)),
                ("visitado", models.BooleanField(default=False)),
            ],
        ),
    ]
